### ISSUE TITLE
Overflow error when uploading large tarball to RCDS

### ISSUE THREAD

**Issue by retzkek** [fermitools/jobsub_lite#287]
From INC000001147326:

> When attempting to submit a job to the grid the following messages appear and repeat every 30 seconds.

```
Traceback (most recent call last):
  File "/opt/jobsub_lite/lib/tarfiles.py", line 343, in wrapper
    response = func(self, *args, **kwargs)
  File "/opt/jobsub_lite/lib/tarfiles.py", line 387, in publish
    return requests.post(url, auth=TokenAuth(self.token), data=tarfile)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 651, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1075, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 996, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 934, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.6/ssl.py", line 903, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 601, in write
    return self._sslobj.write(data)

OverflowError: string longer than 2147483647 bytes

Will retry in 30 seconds
```

Probably need to upload tarballs as chunks, which `requests` will do if a generator is passed as the body. https://requests.readthedocs.io/en/latest/user/advanced/#chunk-encoded-requests

It gets a bit messy since we need the hash before starting the upload unfortunately.

**Comment by marcmengel** [comment]
https://requests.readthedocs.io/en/latest/user/advanced/#streaming-uploads
