### ISSUE TITLE
Improvements to TarfilePublisherHandler

### ISSUE THREAD

**Issue by shreyb** [fermitools/jobsub_lite#468]
@DrDaveD and I were troubleshooting an imbalance on publishes between the RCDS servers, and he had a couple of suggestions with how we handle retries in the `TarfilePublisherHandler`

https://github.com/fermitools/jobsub_lite/blob/1cf07430b89cfb3e008d32f3b5d5e8d9fff0b8e5/lib/tarfiles.py#L446

# Idea 1

We basically do three operations maximum:  Exists query, Publish request (if not Exists), and then Exists queries (in retry loop until we exhaust retries).  Currently, we switch between servers for each one, and there's not really a reason to do so.  This also obscures any potential issue with a particular server, since we keep switching.  So between the first Exists, and Publish, it'd be nice to just stick with one server unless there's an actual exception.  Between the Publish and the next Exists (and any following retries), we can switch servers.

# Idea 2

For any retries, since we have multiple servers, we currently wait for 30 seconds between retries, even on first failure.  It'd be better if for the first failure, we *immediately* switch servers and retry, and then if there's a second failure, then wait the 30 seconds thereafter between retries.  This should be as easy as doing something like this in the `pubapi_operation` retry loop:

```python
_retry_interval_sec = 0
retry_count = itertools.count()
while True:
  try:
      request()
  except:
      switch_servers()
      rest_of_stuff()
      time.sleep(_retry_interval_sec)
      _retry_interval_sec = RETRY_INTERVAL_SEC
```

We do something similar to this in the tarball discovery code in the job wrapper scripts, where we check all four repositories for a tarball hash, then if we don't find the tarball, we wait 30 seconds and try again.

**Comment by shreyb** [comment]
Idea 1 is implemented in commit 5097503c4.

**Comment by shreyb** [comment]
Idea 2 is now done.  I have to think of a good way to test the following cases:

1) Check to make sure Idea 1 works (make sure exists and publish for a new tarball works)
2) Somehow make the publish fail for Idea 2.  We can then check:
   1) Do we retry immediately the first time?
   2) Do we switch servers?
3)  For the exists calls, we can test the rest of Idea 2:  that is, make sure that if we set fixed_server either way, that it is respected.  This can even be tested from the python IDE.

**Comment by shreyb** [comment]
Tests (1) and (2) work:

```
Using PubAPI server rcds01.fnal.gov
Calling URL https://rcds01.fnal.gov/pubapi/exists?cid=nova%2F242483b27f8e9d987653fd7dd48f7490afee0db1dbbec085cc881c7bfbd04c8b


Using RCDS to publish tarball
cid: nova/242483b27f8e9d987653fd7dd48f7490afee0db1dbbec085cc881c7bfbd04c8b
Using PubAPI server rcds01.fnal.gov
Calling URL https://rcds01.fnal.gov/pubapi/publish?cid=nova%2F242483b27f8e9d987653fd7dd48f7490afee0db1dbbec085cc881c7bfbd04c8b
Checking to see if uploaded file is published on RCDS for CID nova/242483b27f8e9d987653fd7dd48f7490afee0db1dbbec085cc881c7bfbd04c8b
Using PubAPI server rcds02.fnal.gov
Calling URL https://rcds02.fnal.gov/pubapi/exists?cid=nova%2F242483b27f8e9d987653fd7dd48f7490afee0db1dbbec085cc881c7bfbd04c8b
Could not locate uploaded file on RCDS.  Will retry in 0 seconds.
Using PubAPI server rcds01.fnal.gov
Calling URL https://rcds01.fnal.gov/pubapi/exists?cid=nova%2F242483b27f8e9d987653fd7dd48f7490afee0db1dbbec085cc881c7bfbd04c8b
Could not locate uploaded file on RCDS.  Will retry in 30 seconds.
Using PubAPI server rcds02.fnal.gov
Calling URL https://rcds02.fnal.gov/pubapi/exists?cid=nova%2F242483b27f8e9d987653fd7dd48f7490afee0db1dbbec085cc881c7bfbd04c8b
Found uploaded file on RCDS.
```

This shows:

1) The first `exists` and `publish` call go to the same server.
2) The first retry happens immediately after the second `exists` call.  We keep switching servers after that.

The job ID for this test is  66940524.0@jobsub01.fnal.gov .  We want to make sure we get a fully-running test job along with test (3) before calling this done.

**Comment by shreyb** [comment]
For the end-to-end test, it turns out that I was using an old script that isn't expected to work any longer.  I reran a test from #324, that's got an updated script, and it worked:

```
$ ~/jobsub_lite/bin/jobsub_submit -G fermilab --tar-file-name dropbox:///home/sbhat/FileUploadTests/testfiles.tar --onsite --debug  file:///home/sbhat/FileUploadTests/tar-file-name.sh 1
```

(the job id was 7723058.0@jobsub05.fnal.gov).  This submission exhibited all the behavior observed before for job 66940524.0@jobsub01.fnal.gov that we expected.

**Comment by shreyb** [comment]
(3) test:

Instantiate `TarfilePublisherHandler` with default setting:

```
$ cd lib/
$ touch /tmp/fake_token
$ python3
...
>>> from tarfiles import TarfilePublisherHandler
>>> from creds import CredentialSet
>>> tfh = TarfilePublisherHandler(cid='test/12345abcde', cred_set=CredentialSet(token='/tmp/fake_token'), verbose=1)
Publishing hash test/12345abcde to RCDS:
Using bearer token located at /tmp/fake_token to authenticate to RCDS
>>> r = tfh.cid_exists()
Using PubAPI server rcds02.fnal.gov
Calling URL https://rcds02.fnal.gov/pubapi/exists?cid=test%2F12345abcde
Traceback (most recent call last):
  File "/home/sbhat/jobsub_lite/lib/tarfiles.py", line 522, in wrapper
    )
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Access denied for url: https://rcds02.fnal.gov/pubapi/exists?cid=test%2F12345abcde
Will retry in 0 seconds
Using PubAPI server rcds01.fnal.gov
Calling URL https://rcds01.fnal.gov/pubapi/exists?cid=test%2F12345abcde
Traceback (most recent call last):
  File "/home/sbhat/jobsub_lite/lib/tarfiles.py", line 522, in wrapper
    )
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Access denied for url: https://rcds01.fnal.gov/pubapi/exists?cid=test%2F12345abcde
Will retry in 30 seconds
Using PubAPI server rcds02.fnal.gov
Calling URL https://rcds02.fnal.gov/pubapi/exists?cid=test%2F12345abcde
Traceback (most recent call last):
  File "/home/sbhat/jobsub_lite/lib/tarfiles.py", line 522, in wrapper
    )
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Access denied for url: https://rcds02.fnal.gov/pubapi/exists?cid=test%2F12345abcde
Will retry in 30 seconds
...
```

Instantiate it with `fixed_server` set to `True`:

```
>>> tfh = TarfilePublisherHandler(cid='test/12345abcde', cred_set=CredentialSet(token='/tmp/fake_token'), fixed_server=True, verbose=1)
Publishing hash test/12345abcde to RCDS:
Using bearer token located at /tmp/fake_token to authenticate to RCDS
>>> r = tfh.cid_exists()
Using PubAPI server rcds01.fnal.gov
Calling URL https://rcds01.fnal.gov/pubapi/exists?cid=test%2F12345abcde
Traceback (most recent call last):
  File "/home/sbhat/jobsub_lite/lib/tarfiles.py", line 522, in wrapper
    )
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Access denied for url: https://rcds01.fnal.gov/pubapi/exists?cid=test%2F12345abcde
Will retry in 0 seconds
Using PubAPI server rcds01.fnal.gov
Calling URL https://rcds01.fnal.gov/pubapi/exists?cid=test%2F12345abcde
Traceback (most recent call last):
  File "/home/sbhat/jobsub_lite/lib/tarfiles.py", line 522, in wrapper
    )
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Access denied for url: https://rcds01.fnal.gov/pubapi/exists?cid=test%2F12345abcde
Will retry in 30 seconds
Using PubAPI server rcds01.fnal.gov
Calling URL https://rcds01.fnal.gov/pubapi/exists?cid=test%2F12345abcde
Traceback (most recent call last):
  File "/home/sbhat/jobsub_lite/lib/tarfiles.py", line 522, in wrapper
    )
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Access denied for url: https://rcds01.fnal.gov/pubapi/exists?cid=test%2F12345abcde
Will retry in 30 seconds
...
```

Looks good.

**Comment by shreyb** [comment]
Also verified (3) with publish calls:

```
>>> tfh = TarfilePublisherHandler(cid='test/12345abcde', cred_set=CredentialSet(token='/tmp/fake_token'), fixed_server=True, verbose=1)
Publishing hash test/12345abcde to RCDS:
Using bearer token located at /tmp/fake_token to authenticate to RCDS
>>> cid.publish("12345")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'cid' is not defined
>>> tfh.publish("12345")
TarfilePublisherHandler is configured to use a fixed RCDS server, however this is being overridden for the duration of the current request.
Using PubAPI server rcds02.fnal.gov
Calling URL https://rcds02.fnal.gov/pubapi/publish?cid=test%2F12345abcde
Traceback (most recent call last):
  File "/home/sbhat/jobsub_lite/lib/tarfiles.py", line 527, in wrapper
    response = func(self, *args, **kwargs)
  File "/home/sbhat/jobsub_lite/lib/tarfiles.py", line 607, in publish
    with open(tarfilename, "rb") as tarfile:
FileNotFoundError: [Errno 2] No such file or directory: '12345'
Will retry in 0 seconds
Using PubAPI server rcds01.fnal.gov
Calling URL https://rcds01.fnal.gov/pubapi/publish?cid=test%2F12345abcde
Traceback (most recent call last):
  File "/home/sbhat/jobsub_lite/lib/tarfiles.py", line 527, in wrapper
    response = func(self, *args, **kwargs)
  File "/home/sbhat/jobsub_lite/lib/tarfiles.py", line 607, in publish
    with open(tarfilename, "rb") as tarfile:
FileNotFoundError: [Errno 2] No such file or directory: '12345'
Will retry in 30 seconds
Using PubAPI server rcds02.fnal.gov
Calling URL https://rcds02.fnal.gov/pubapi/publish?cid=test%2F12345abcde
Traceback (most recent call last):
  File "/home/sbhat/jobsub_lite/lib/tarfiles.py", line 527, in wrapper
    response = func(self, *args, **kwargs)
  File "/home/sbhat/jobsub_lite/lib/tarfiles.py", line 607, in publish
    with open(tarfilename, "rb") as tarfile:
FileNotFoundError: [Errno 2] No such file or directory: '12345'
Will retry in 30 seconds
```

We see here that the fixed_server behavior is overridden for the publish call, as is intended.

This is ready for a PR.
